---
title: "`r params$title`"
subtitle: '`r params$subtitle`'
author: '`r params$author`'
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: 
  html_document:
    theme: united
    toc: true
    toc_depth: 3
  pdf_document:
    toc: true
    toc_depth: 3
    highlight: zenburn
  word_document:
    toc: true
    toc_depth: 3
    highlight: "tango"
params:
  traits: "no data"
  factors: "no data"
  rep: "no data"
  design: "no data"
  data: "no data"
  maxp: "no data"
  title: "no data"
  subtitle: "no data"
  author: "no data"
---

```{r, echo = FALSE}
library(knitr)

traits <- params$traits
factors <- params$factors
rep <- params$rep
design <- params$design
data <- params$data
maxp <- params$maxp

# Compute checks with one trait

lc <- ck.f(traits[1], factors, rep, data)

# Texts for levels

text.levels <- lc$nl[1]
for (i in 2:(lc$nf - 1))
  text.levels <- paste0(text.levels, ', ', lc$nl[i])
text.levels <- paste0(text.levels, ', and ' lc$nl[lc$nf])

# Text for design

if (design == 'crd')
  text.design <- 'completely randomized design'
if (design == 'rcbd')
  text.design <- 'randomized complete block design'
  
# Everything as character

for (i in 1:nf) 
  data[, factors[i]] <- as.character(data[, factors[i]])
data[, rep] <- as.character(data[, rep])
```

# 1. Model specification and data description

The data frame has data for a full factorial with `r lc$nf` factors with `r text.levels` levels. The experimental design is a `r text.design` with `r nlevels(as.factor(data[, rep]))` replications. 

In this model we assume that the errors are independent and have a normal distribution with common variance.

```{r, include = FALSE}
out <- NULL
for (i in 1:length(traits)) {
  lc <- ck.f(traits[i], factors, rep, data)
  if (lc$c1 == 1 & lc$c2 == 1 & lc$c3 == 1 & lc$pmis <= maxp)
    out <- c(out, knit_expand('child_f.Rmd'))
  else
    out <- c(out, knit_expand('child_f_fail.Rmd'))
}
```

`r paste(knit(text = out), collapse = '\n')`
