---
title: "`r params$title`"
subtitle: '`r params$subtitle`'
author: '`r params$author`'
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: 
  html_document:
    theme: united
    toc: true
    toc_depth: 3
  pdf_document:
    toc: true
    toc_depth: 3
    highlight: zenburn
  word_document:
    highlight: "tango"
    toc: true
    toc_depth: 3
params: 
  dfr: "no data"
  vars: "no data"
  line: "no data"
  tester: "no data"
  rep: "no data"
  title: "no data"
  subtitle: "no data"
  author: "no data"
---

```{r global_options, include = FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, comment = NA)
```

```{r}
# Pass arguments

dfr <- params$dfr
vars <- params$vars
line <- params$line
tester <- params$tester
rep <- params$rep

# Define genotypes id

dfr[, 'geno'] <- paste(dfr[, line], dfr[, tester])
```

```{r include = FALSE}
lc.gd <- ck.lxt(dfr, line, tester)

out <- NULL
for (i in 1:length(vars)) {
  lc <- ck.rcbd(dfr, vars[i], 'geno', rep)
  if (lc$ng.0 == 0 & lc$nrep > 1 & lc$ng.mult == 0 & lc$nmis == 0 &
      lc.gd$c1 == TRUE & lc.gd$c2 == TRUE & lc.gd$c3 == TRUE) {
    out <- c(out, knit_expand('child_lxt.Rmd'))
  } else {
    out <- c(out, knit_expand('child_lxt_fail.Rmd'))
  }
}
```

`r paste(knit(text = out), collapse = '\n')`
