---
title: "`r params$title`"
subtitle: '`r params$subtitle`'
author: '`r params$author`'
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: 
  html_document:
    theme: united
    toc: true
    toc_depth: 3
  pdf_document:
    toc: true
    toc_depth: 3
    highlight: zenburn
  word_document:
    highlight: "tango"
    toc: true
    toc_depth: 3
params:
  traits: "no data"
  set: "no data"
  male: "no data"
  female: "no data"
  progeny: "no data"
  rep: "no data"
  model: "no data"
  data: "no data"
  title: "no data"
  subtitle: "no data"
  author: "no data"
---

```{r, echo = FALSE}
library(knitr)

traits <- params$traits
set <- params$set
male <- params$male
female <- params$female
progeny <- params$progeny
rep <- params$rep
model <- params$model
data <- params$data
```

# 1. Model specification and data description

`r if (model == 1) {"This is a North Carolina I genetic design."}`
`r if (model == 2) {"This is a North Carolina II genetic design."}`
`r if (model == 3) {"This is a North Carolina III genetic design."}`

```{r, include = FALSE}
out <- NULL

for (i in 1:length(traits))
  out <- c(out, knit_expand('child_nc.Rmd'))
```

`r paste(knit(text = out), collapse = '\n')`
