---
title: "Report for a MET with a RCBD"
author: '`r params$author`'
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: 
  html_document:
    theme: united
  pdf_document:
    toc: true
    highlight: zenburn
  word_document:
    highlight: "tango"
params: 
  trait: "no data"
  geno: "no data"
  env: "no data"
  rep: "no data"
  data: "no data"
  maxp: "no data"
  author: "no data"
---

```{r, echo = FALSE}
trait <- params$trait
geno <- params$geno
env <- params$env
rep <- params$rep
data <- params$data
maxp <- params$maxp
model <- suppressWarnings(st4gi::aovmet(trait, geno, env, rep, data, maxp, anova = FALSE))
```

`r if(model$lc$c1 == 1 & model$lc$c2 == 1) {"You have fitted a linear model for a multi environment trial (MET) with a RCBD in each environment. The ANOVA table for your model is:"}`

```{r, echo = FALSE}
model$at
```

`r if(model$lc$c3 == 0) paste("You have some missing values (", format(model$est.data$est.prop*100, digits = 4), "%) and they have been estimated before running ANOVA.")`

