---
title: "Report for a MET with a RCBD"
author: '`r params$author`'
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: 
  html_document:
    theme: united
  pdf_document:
    toc: true
    highlight: zenburn
  word_document:
    highlight: "tango"
params: 
  traits: "no data"
  geno: "no data"
  env: "no data"
  rep: "no data"
  data: "no data"
  maxp: "no data"
  author: "no data"
---

```{r, echo = FALSE}
traits <- params$traits
geno <- params$geno
env <- params$env
rep <- params$rep
data <- params$data
maxp <- params$maxp
```

# Model specification and data description

There is data from `r nlevels(as.factor(data[, env]))` environments and `r nlevels(as.factor(data[, geno]))` genotypes. In each environment the genotypes were evaluated using a randomize complete block design with `r nlevels(as.factor(data[, rep]))` blocks. The statistical model is
$$
y_{ijk} = \mu + \alpha_i + \beta_j + (\alpha\beta)_{ij} + \gamma_{k(j)} + \epsilon_{ijk}
$$
where

* $y_{ijk}$ is the observed response with genotype $i$, environment $j$, and block $k$ nested in environment $j$.
* $\mu$ is the mean response over all genotypes, environments and blocks.
* $\alpha_i$ is the fixed effect for genotype $i$.
* $\beta_j$ is the fixed effect for environment $j$.
* $(\alpha\beta)_{ij}$ is the fixed interaction effect between genotype $i$ and environment $j$.
* $\gamma_{k(j)}$ is the random effect of block $k$ nested in environment $j$.
* $\epsilon_{ijk}$ is the error term.

In this model we assume that the errors are independent and have a normal distribution with common variance, that is, $(\epsilon_{ijk} \sim N(0,\sigma_{\epsilon}^2))$.

